server:
  port: 8888
logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://192.168.0.17:3306/security-login?useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8mb4
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
mybatis:
  configuration:
    map-underscore-to-camel-case: true